server:
  port: 9000 # 端口

spring:
  application:
    name: zuul-server # 应用名称

# 配置Eureka Server注册中心
eureka:
  instance:
    # 主机名, 不配置的时候将根据操作系统的主机名称来获取
    hostname: localhost
    # 是否开启IP地址注册
    prefer-ip-address: true
    # 主机地址+端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      # 注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true

# 路由规则
zuul:
  # 路由前缀
  prefix: /api
  #ignored-patterns: /**/order/**  # URL 地址排除，排除所有包含 /order/ 的路径
  # 不受路由排除影响
  routes:
    product-service: # 路由 id 自定义
      path: /product-service/**   # 配置请求 url 的映射路径
      url: http://localhost:9090/ # 映射路径对应的微服务地址
      serviceId: product-service  # 根据 serviceId 自动从注册中心获取服务地址并转发请求
    order-service:
      path: /order-service/**
      url: http://localhost:9091/
      serviceId: order-service  # 根据 serviceId 自动从注册中心获取服务地址并转发请求